### ISSUE TITLE
dead links on website but github is correct

### ISSUE THREAD

**Issue by llamabyte** [RGB-WG/rgb.tech#17]
At  https://rgb.tech/governance/

under the interfaces section, links related to section :

>"[LNP/BP Standards Association](https://rgb.tech/governance/interfaces/LNP/BP) maintains [standards](https://rgb.tech/governance/interfaces/LNPBPs)"

are incorrect and lead to 404.

In github they are correct at the bottom in the code but not on the website, here: 

https://github.com/RGB-WG/rgb.tech/blob/master/content/governance/interfaces.md

![link error](https://github.com/RGB-WG/rgb.tech/assets/130471564/0a3c1292-1605-49e8-9b0e-72da141ae35e)
![link error2](https://github.com/RGB-WG/rgb.tech/assets/130471564/536d46d2-3dec-48d5-a410-6153902b2700)

**Comment by dr-orlovsky** [comment]
Thank you, fixed!
