### ISSUE TITLE
rgb-node install 

### ISSUE THREAD

**Issue by zhangzzgz** [RGB-WG/rgb.tech#20]
In attempting to install rgb-node, I continually encounter errors related to recursion limits. Despite modifying the code's recursion_limit from '256' to '512', the issue persists.

error[E0275]: overflow evaluating the requirement `D: std::io::Read`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "512"]` attribute to your crate (`bitcoin_scripts`)
  = note: required for `&mut D` to implement `std::io::Read`
  = note: 256 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut ...` to implement `std::io::Read`
  = note: the full type name has been written to '/tmp/cargo-installSMLsjZ/release/deps/bitcoin_scripts-65df17898e86b5ed.long-type-1557081754048186676.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `bitcoin_scripts` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `store_daemon v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-installSMLsjZ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by dr-orlovsky** [comment]
https://github.com/RGB-WG/rgb-node/issues/257
