### ISSUE TITLE
Use RGB buttons and links are broken

### ISSUE THREAD

**Issue by jeffrey-l-turner** [RGB-WG/rgb.tech#29]
All of the links & under the "Use RGB" section do not go anywhere
![image](https://github.com/user-attachments/assets/58ce2dd4-b4e3-4998-8c18-2e8afca338bc)

All the links in this section give 404 errors

**Comment by dr-orlovsky** [comment]
Finally got to this. Fixed in https://github.com/RGB-WG/rgb.tech/commit/c43fdcbf67729f03626e9a959a1f28dd94c2eb02
