### ISSUE TITLE
grammatical error's on website

### ISSUE THREAD

**Issue by llamabyte** [RGB-WG/rgb.tech#5]
This was written by Giacomo right ? It makes similar english errors he does. This is my little contribution to the credibility of this great project !

https://rgb.tech/

>Scalability
>it is sharded from the day 1 and is fully interoperable with layer 2 scalability solutions.

....it is sharded from **~the~** day 1 and is fully interoperable >with layer 2 scalability solutions.

>Privacy
>No chain analysis is possible due to the absence of transaction graph in blockchain.

Privacy
No chain analysis is possible due to the absence of **a** transaction graph in blockchain. 

> Bitcoin & Lightning

RGB is a native member of Bitcoin and Lightning network ecosystem, bringing rich smart contracts in a scalable way to the World's most secure and censorship-resistant cryptocurrency.

https://rgb.tech/program/contractum/

>- and not required to be validated by anyone else than the contract participants (hence scalability).

should be

and **are** not required......

>RGB makes bitcoin to pass beyond limitations of [CIA triad](https://www.coursera.org/articles/cia-triad) via achieving different properties on different layers:

RGB **allows** Bitcoin to pass beyond **the** ...

There is more, let me know if this is useful and i will do a pass through.

**Comment by dr-orlovsky** [comment]
No, it is not written by Giacomo but by me. We are both non-native speakers thus the errors might be similar. Thank you very much, this is useful - I will work on fixing this in the meantime.
